#show link: set text(blue)

= Prerequisites

Comfort with these topics will make the rest easier:

- #link("https://www.youtube.com/watch?app=desktop&v=DGojI9xcCfg")[Working With Images in Julia (MIT 18.S191, lecture 3)] --- image arrays, color channels, broadcasting.
- #link("https://www.youtube.com/watch?v=E8HeD-MUrjY")[The Fast Fourier Transform (Brunton)] and #link("https://www.youtube.com/watch?v=gGEBUdM0PVc")[Image Compression and the FFT] --- FFT in one variable; complex-number basics.
- #link("https://github.com/GiggleLiu/tutorial-tensornetwork")[Tutorial on Tensor Networks (GiggleLiu)] --- tensor network notation and contractions.
- #link("https://www.youtube.com/watch?v=dJz1klEutRY")[Manopt.jl: Optimisation on Riemannian Manifolds (JuliaCon 2022)] --- Riemannian optimization basics.

= Setup

```sh
git clone https://github.com/nzy1997/ParametricDFT.jl
cd ParametricDFT.jl
julia --project=examples -e 'using Pkg; Pkg.instantiate()'
```

`--project=examples` activates `examples/Project.toml`, which carries demo dependencies (CairoMakie, FFTW, MLDatasets, ImageQualityIndexes, NPZ) on top of the library itself.

= Run the example

== Run it

```sh
julia --project=examples examples/mera_demo.jl
```

Trains a `MERABasis` on synthetic 16$times$16 images (gradient + circle), then compresses and reconstructs them, comparing the result against `QFTBasis` and the classical FFT.

== What you'll see

The script prints seven numbered steps:

1. Generate synthetic dataset --- 20 training + 5 test images, 16$times$16.
2. Build untrained QFT and MERA bases; print parameter counts.
3. Train both bases for 10 epochs (`MSELoss` with top-`k` truncation in the loss, batch size 16; the actual `k` is printed at this step).
4. Save training-loss plots.
5. Save trained bases as JSON.
6. Evaluate compression at 95% / 90% / 80% / 70% keep-ratios; print MSE and PSNR for QFT, MERA, classical FFT side by side.
7. Save a reconstruction comparison PNG.

Total runtime: a few minutes on CPU.

== Output to look at

In `examples/MERADemo/`:

- `training_plots/*.png` --- loss curves per basis.
- `trained_qft.json`, `trained_mera.json` --- saved bases (load with `load_basis`).
- `compression_comparison.png` --- visual comparison.

= Code map

#table(
  columns: 2,
  [*Group*], [*Files*],
  [Bases], [`basis.jl` (abstract type), `qft.jl`, `entangled_qft.jl`, `tebd.jl`, `mera.jl`],
  [Loss & manifolds], [`loss.jl`, `manifolds.jl`],
  [Optimizers], [`optimizers.jl`, `einsum_cache.jl`],
  [Training pipeline], [`training.jl`],
  [Compression & I/O], [`compression.jl`, `serialization.jl`],
  [Visualization], [`visualization.jl`, `circuit_visualization.jl`],
  [GPU extension], [`ext/CUDAExt.jl`],
  [Tests], [`test/runtests.jl` and per-module `*_tests.jl`],
)

= Where to read more

- `note/main.typ` --- math (manifolds, retraction, batched einsum, Riemannian Adam).
- GitHub Pages #link("https://nzy1997.github.io/ParametricDFT.jl/dev/training/")[Training] --- API reference autogenerated from source docstrings.
- GitHub Pages #link("https://nzy1997.github.io/ParametricDFT.jl/dev/performance/")[Performance] --- measured speed-ups over a Manopt baseline; batch-size decision rule.
- `examples/basis_demo.jl` --- full QFT / Entangled / TEBD comparison on MNIST or QuickDraw (heavier; requires dataset download).
- `examples/circuit_visualization.jl` --- generate PNG circuit diagrams for any basis.
